apiVersion: v1
kind: Pod
metadata:
  name: my-frontend-pod
  labels:
    tier: frontend
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: ENV
          value: "dev"
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
